CREATE TABLE [Canciones] (
[ID] INTEGER  PRIMARY KEY AUTOINCREMENT NOT NULL,
[Nombre] VARCHAR(50)  NULL,
[Album] VARCHAR(50)  NULL,
[Artista] VARCHAR(50)  NULL,
[Genero] VARCHAR(50)  NULL,
[Alan] VARCHAR(50)  NULL
);